package com.doomsdaybot.samsungmvp.scenario

enum class StepRequirementMode {
    ALL,
    ANY,
}

data class ScenarioTemplateDefinition(
    val templateId: String,
    val feature: BotFeature,
    val name: String,
    val action: String,
    val stepId: String = "",
    val priority: Int,
    val threshold: Float,
    val delayMs: Long = 800L,
    val requiredSteps: Set<String> = emptySet(),
    val requirementMode: StepRequirementMode = StepRequirementMode.ALL,
    val repeatStep: Boolean = false,
    val allowRuntimeResume: Boolean = false,
    val requiredPrizeRepeat: Boolean? = null,
    val clickOffsetX: Int = 0,
    val clickOffsetY: Int = 0,
    val referenceWidth: Int = 1280,
    val referenceHeight: Int = 720,
) {
    val assetPath: String
        get() = "scenario_templates/${feature.id}/$templateId.png"
}

object BuiltInScenarioCatalog {
    val templates: List<ScenarioTemplateDefinition> = listOf(
        template(
            "4354be9a-4eec-5775-b701-9d34bd2d6c78",
            BotFeature.HEAL,
            "Собрать вылеченные войска",
            "collect_healed_troops",
            "collect_finished",
            1,
            0.70f,
            repeatStep = true,
        ),
        template(
            "a9233d02-5e5b-5cbf-ab38-c10ba4ba18e2",
            BotFeature.HEAL,
            "Открыть панель лечения",
            "click",
            "healing_overview",
            2,
            0.78f,
            repeatStep = true,
        ),
        template(
            "47523348-94a8-5265-8039-6792377624f1",
            BotFeature.HEAL,
            "Открыть госпиталь с ранеными",
            "open_healing_hospital",
            "open_wounded",
            10,
            0.74f,
            repeatStep = true,
        ),
        template(
            "ff960cad-b95b-5f60-8722-49b73b505f5e",
            BotFeature.HEAL,
            "Начать лечение обычными ресурсами",
            "heal_troops",
            "start_healing",
            20,
            0.88f,
            requiredSteps = setOf("open_wounded"),
            repeatStep = true,
        ),

        template(
            "5433ee02-02e3-56b8-a36d-3ac83cee87cd",
            BotFeature.ZOMBIE_HUNT,
            "Открыть регион",
            "open_world_search",
            "world_search",
            9,
            0.88f,
        ),
        template(
            "ec60c4df-1515-5b76-b4bd-bed7f3f780ac",
            BotFeature.ZOMBIE_HUNT,
            "Открыть поиск",
            "click",
            "world_search",
            10,
            0.82f,
            repeatStep = true,
        ),
        template(
            "48c3b722-acdd-546f-b92b-053e68720285",
            BotFeature.ZOMBIE_HUNT,
            "Выбрать поиск зомби",
            "click",
            "zombie_icon",
            20,
            0.78f,
            requiredSteps = setOf("world_search"),
            repeatStep = true,
        ),
        template(
            "64bc232e-39ff-5ab3-bba8-61ee908c194c",
            BotFeature.ZOMBIE_HUNT,
            "Найти зомби заданного уровня",
            "zombie_search",
            "search",
            30,
            0.88f,
            requiredSteps = setOf("zombie_icon"),
            repeatStep = true,
        ),
        template(
            "9f6d2de7-fa3c-51f3-a0d7-f9bb5f2ec4df",
            BotFeature.ZOMBIE_HUNT,
            "Атаковать найденных зомби",
            "zombie_attack",
            "attack",
            40,
            0.88f,
            requiredSteps = setOf("search"),
            repeatStep = true,
        ),
        template(
            "a0c10994-649e-5231-82af-a99c2650a2f3",
            BotFeature.ZOMBIE_HUNT,
            "Создать отряд для охоты",
            "click",
            "create_squad",
            50,
            0.88f,
            requiredSteps = setOf("attack"),
            repeatStep = true,
        ),
        template(
            "b0e79e43-1f18-5775-a3ee-4e5b0cf632a1",
            BotFeature.ZOMBIE_HUNT,
            "Отправить отряд на зомби",
            "click",
            "march",
            60,
            0.88f,
            requiredSteps = setOf("create_squad"),
            repeatStep = true,
        ),

        template(
            "100556d4-8c2e-5ad2-9859-9f93ac1f3270",
            BotFeature.PRIZE_HUNT,
            "Нет развертываемого отряда для охоты",
            "click",
            "no_deployable_squad",
            1,
            0.82f,
            requiredSteps = setOf("prepare", "open_squad"),
            requirementMode = StepRequirementMode.ANY,
            allowRuntimeResume = true,
            clickOffsetY = 175,
        ),
        template(
            "8ade1337-6b06-5c45-81e3-217fbf1905c4",
            BotFeature.PRIZE_HUNT,
            "Открыть кампанию",
            "click",
            "campaign",
            10,
            0.84f,
        ),
        template(
            "3372940c-2504-5ef8-abb0-a3b11c495a84",
            BotFeature.PRIZE_HUNT,
            "Открыть охоту за призом",
            "click",
            "event",
            11,
            0.88f,
            requiredSteps = setOf("campaign"),
        ),
        template(
            "f7dab017-6c93-56ac-a704-e976ecd13145",
            BotFeature.PRIZE_HUNT,
            "Войти в охоту за призом",
            "click",
            "enter",
            12,
            0.74f,
            requiredSteps = setOf("event"),
        ),
        template(
            "66a0b0e4-6950-5773-bc59-425cd42d6c53",
            BotFeature.PRIZE_HUNT,
            "Запустить охоту или настроить отряд",
            "prize_start_or_prepare",
            "open_squad",
            13,
            0.84f,
            requiredSteps = setOf("enter"),
        ),
        template(
            "c7aef43d-fbec-5fe4-a172-63c7e2d1efc7",
            BotFeature.PRIZE_HUNT,
            "Заполнить отряд для охоты",
            "prize_prepare",
            "prepare",
            14,
            0.88f,
            requiredSteps = setOf("open_squad"),
        ),
        template(
            "8debc986-601b-5091-bd3a-9084944ea4b1",
            BotFeature.PRIZE_HUNT,
            "Отправить отряд на охоту",
            "click",
            "deploy",
            16,
            0.88f,
            requiredSteps = setOf("prepare", "open_squad"),
            requirementMode = StepRequirementMode.ANY,
        ),
        template(
            "e49ff4fa-ea03-5ff6-919c-05ed82f6c9ff",
            BotFeature.PRIZE_HUNT,
            "Выйти после поражения без возрождения",
            "click",
            "safe_exit_current",
            17,
            0.88f,
            requiredSteps = setOf("deploy", "enter"),
            requirementMode = StepRequirementMode.ANY,
            repeatStep = true,
            allowRuntimeResume = true,
        ),
        template(
            "1dcf30f1-1262-5ef1-ae18-f2cff53bcc65",
            BotFeature.PRIZE_HUNT,
            "Выйти после поражения без возрождения",
            "click",
            "safe_exit",
            18,
            0.88f,
            requiredSteps = setOf("safe_exit_current", "deploy", "enter"),
            requirementMode = StepRequirementMode.ANY,
            repeatStep = true,
            allowRuntimeResume = true,
            requiredPrizeRepeat = false,
        ),
        template(
            "c6afae35-86fb-533a-b672-6a8926f365d6",
            BotFeature.PRIZE_HUNT,
            "Повторить охоту",
            "click",
            "again",
            19,
            0.88f,
            requiredSteps = setOf("safe_exit_current", "deploy", "enter"),
            requirementMode = StepRequirementMode.ANY,
            repeatStep = true,
            allowRuntimeResume = true,
            requiredPrizeRepeat = true,
        ),
        template(
            "ee9027f3-5c5f-5745-b71a-86e285e25aa9",
            BotFeature.PRIZE_HUNT,
            "Начать повторный подбор",
            "click",
            "match",
            20,
            0.88f,
            requiredSteps = setOf("again"),
            repeatStep = true,
            requiredPrizeRepeat = true,
        ),
        template(
            "df4c5499-0ef1-54cd-81c8-8e9ef9fb2a4b",
            BotFeature.PRIZE_HUNT,
            "Подтвердить повторный подбор",
            "click",
            "confirm",
            21,
            0.88f,
            requiredSteps = setOf("match"),
            repeatStep = true,
            requiredPrizeRepeat = true,
        ),
    )

    private fun template(
        templateId: String,
        feature: BotFeature,
        name: String,
        action: String,
        stepId: String,
        priority: Int,
        threshold: Float,
        requiredSteps: Set<String> = emptySet(),
        requirementMode: StepRequirementMode = StepRequirementMode.ALL,
        repeatStep: Boolean = false,
        allowRuntimeResume: Boolean = false,
        requiredPrizeRepeat: Boolean? = null,
        clickOffsetY: Int = 0,
    ) = ScenarioTemplateDefinition(
        templateId = templateId,
        feature = feature,
        name = name,
        action = action,
        stepId = stepId,
        priority = priority,
        threshold = threshold,
        requiredSteps = requiredSteps,
        requirementMode = requirementMode,
        repeatStep = repeatStep,
        allowRuntimeResume = allowRuntimeResume,
        requiredPrizeRepeat = requiredPrizeRepeat,
        clickOffsetY = clickOffsetY,
    )
}
